### ISSUE TITLE
Junction deviation

### ISSUE THREAD

**Issue by sllo13** [ChadDevOps/Marlin-Ender-3-Max#1]
Hello,
Do you have junction deviation enabled in the bin files?

Are the configuration files posted here the latest that you used to compile the latest released version?

Thank you

**Comment by ChadDevOps** [comment]
CLASSIC_JERK is enabled by default.  You can override with  `M205 X Y Z E`. I haven't had the chance to test Jerk settings yet. Any recommendations? And yes, the config files that are posted are used for the compiled version. I comment out my upgraded mods and revert to the stock settings (best guess).

**Comment by ChadDevOps** [comment]
Disabled classic jerk. https://github.com/ChadDevOps/Marlin-Ender-3-Max/releases/tag/v0.1.3b-beta

**Comment by sllo13** [comment]
Perfect!!!!!!!!!
