### ISSUE TITLE
Filament runout/Filament change M600 cunfused procedere

### ISSUE THREAD

**Issue by Jumbo125** [ChadDevOps/Marlin-Ender-3-Max#2]
Hello ChadDevOps

i hope it's okay to ask you about my issue......
I also use your marlin version for my ender 3 max and pass something in the source code for me, cause i used mesh bed leveling since a few month... It works great!
But if i use the M600 Gcode, it's not so perfect.
1. The noozle goes to park-position
2. after a few minutes the LCD shows heat noozle -> i'll do this.
3. Load Filament -> i accept
4. all works very fine!
5. After load Filament i click continue on the LCD
6. The noozle goes back to the last print-position
7. NOW it will be confused..... The noozle start the printing, Exactly at the Beginn - Suddenly the extruder RETRACT some Filament and than it feed normaly and the noozle move.... Now it works normlay. But the first 30 seconds, i don't get any Filament, cause the extruder retracted a little Distance of the filament, before start noozle move-printing. 

My code is:

> #define ADVANCED_PAUSE_FEATURE
> #if ENABLED(ADVANCED_PAUSE_FEATURE)
>   #define PAUSE_PARK_RETRACT_FEEDRATE         60  // (mm/s) Initial retract feedrate.
>   #define PAUSE_PARK_RETRACT_LENGTH            2  // (mm) Initial retract.
>                                                   // This short retract is done immediately, before parking the nozzle.
>   #define FILAMENT_CHANGE_UNLOAD_FEEDRATE     20  // (mm/s) Unload filament feedrate. This can be pretty fast.
>   #define FILAMENT_CHANGE_UNLOAD_ACCEL        25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
>   #define FILAMENT_CHANGE_UNLOAD_LENGTH      100  // (mm) The length of filament for a complete unload.
>                                                   //   For Bowden, the full length of the tube and nozzle.
>                                                   //   For direct drive, the full length of the nozzle.
>                                                   //   Set to 0 for manual unloading.
>   #define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE   6  // (mm/s) Slow move when starting load.
>   #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     0  // (mm) Slow length, to allow time to insert material.
>                                                   // 0 to disable start loading and skip to fast load only
>   #define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE  20  // (mm/s) Load filament feedrate. This can be pretty fast.
>   #define FILAMENT_CHANGE_FAST_LOAD_ACCEL     25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
>   #define FILAMENT_CHANGE_FAST_LOAD_LENGTH     0  // (mm) Load length of filament, from extruder gear to nozzle.
>                                                   //   For Bowden, the full length of the tube and nozzle.
>                                                   //   For direct drive, the full length of the nozzle.
>   //#define ADVANCED_PAUSE_CONTINUOUS_PURGE       // Purge continuously up to the purge length until interrupted.
>   #define ADVANCED_PAUSE_PURGE_FEEDRATE        3  // (mm/s) Extrude feedrate (after loading). Should be slower than load feedrate.
>   #define ADVANCED_PAUSE_PURGE_LENGTH         50  // (mm) Length to extrude after loading.
>                                                   //   Set to 0 for manual extrusion.
>                                                   //   Filament can be extruded repeatedly from the Filament Change menu
>                                                   //   until extrusion is consistent, and to purge old filament.
>   #define ADVANCED_PAUSE_RESUME_PRIME          0  // (mm) Extra distance to prime nozzle after returning from park.
>   //#define ADVANCED_PAUSE_FANS_PAUSE             // Turn off print-cooling fans while the machine is paused.
> 
>                                                   // Filament Unload does a Retract, Delay, and Purge first:
>   #define FILAMENT_UNLOAD_PURGE_RETRACT       13  // (mm) Unload initial retract length.
>   #define FILAMENT_UNLOAD_PURGE_DELAY       5000  // (ms) Delay for the filament to cool after retract.
>   #define FILAMENT_UNLOAD_PURGE_LENGTH         8  // (mm) An unretract is done, then this length is purged.
>   #define FILAMENT_UNLOAD_PURGE_FEEDRATE      25  // (mm/s) feedrate to purge before unload
> 
>   #define PAUSE_PARK_NOZZLE_TIMEOUT           60  // (seconds) Time limit before the nozzle is turned off for safety.
>   #define FILAMENT_CHANGE_ALERT_BEEPS         10  // Number of alert beeps to play when a response is needed.
>   #define PAUSE_PARK_NO_STEPPER_TIMEOUT           // Enable for XYZ steppers to stay powered on during filament change.
> 
>   #define PARK_HEAD_ON_PAUSE                    // Park the nozzle during pause and filament change.
>   //#define HOME_BEFORE_FILAMENT_CHANGE           // If needed, home before parking for filament change
> 
>   //#define FILAMENT_LOAD_UNLOAD_GCODES           // Add M701/M702 Load/Unload G-codes, plus Load/Unload in the LCD Prepare menu.
>   //#define FILAMENT_UNLOAD_ALL_EXTRUDERS         // Allow M702 to unload all extruders above a minimum target temp (as set by M302)
> #endif

where can fix it in the source code? 

I tried the Filament Runout Sensor and there is also one confused step....
1. End of Filament, the filament detector check Runout.
2. The noozl go to park position
3. On the LCD display can i chosse "Heat noozle"
4. Then Load filament.
-----All functions work great
5. On the display are two options: Purge more filament or continue
6. I click on continue, cause the filament is already in the noozle.
7. (Now comes the Problem) The noozle goes from the par-position to the last print-position. BUT on the little way from the park-position to the "restart" point, the extruder extruded a little bit filament. This goes out of the noozle and will be stay on the way.
8. continue the printing

Now my question: where can i define the little sequenze, from the park station-to-the-continue-point? I don't want any extrusion during this few seconds(during the drive from the park-position to the print object).

Thank you a lot!

**Comment by Jumbo125** [comment]
Problem was a bug. It works after update to 2.0.8

**Comment by ChadDevOps** [comment]
> Problem was a bug. It works after update to 2.0.8

That's great! I wasn't seeing this issue, so I was stumped. I updated from the latest bug-fix branch a few weeks ago locally, but have yet to push it to github, so that was probably why I couldn't reproduce it. I'll work on updating to the latest commit and get that pushed sometime next week.

**Comment by Jumbo125** [comment]
It works great now. So i think i will not update to the next verison. Never change a Winnnig team ;-)
