### ISSUE TITLE
Probe on wrong side

### ISSUE THREAD

**Issue by Light-oneNL** [ChadDevOps/Marlin-Ender-3-Max#4]
Since you're probe is on the right side of the nozzle and mine is on the left i wanted to compile my own firmware with yours. but i cannot compile it. keep getting errors like 
**Fatal error: can't create .pio\build\STM32F103RE_creality\SrcWrapper\src\HAL\stm32yyxx_hal_dsi.c.o: No such file or directory**
And so on, i've tried the Marlin-2.0.9.2 firmware, but it also throws me alot of errors.

Can you kick-start me where to start this journey?

**Comment by ChadDevOps** [comment]
For compiling/building firmware, I followed Dr. Vax's tutorial here: https://youtu.be/qPDBNBgdW6o?t=680

My probe is on the left when looking at the printer from the front.

**Comment by ChadDevOps** [comment]
Another guide: https://3dprintscape.com/marlin-firmware-on-creality-board-complete-guide/

**Comment by Light-oneNL** [comment]
I've got the problem fixed, in the menu of the printer i can set de offsets of the probe.
